apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultline-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultline-web
  template:
    metadata:
      labels:
        app: vaultline-web
    spec:
      containers:
      - name: web
        image: awi2005/vaultline-web:latest
        ports:
        - containerPort: 80
