apiVersion: v1
kind: Service
metadata:
  name: vaultline-web-service
  namespace: default
spec:
  selector:
    app: vaultline-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
